CREATE USER 'pcmadmin'@'localhost' IDENTIFIED BY 'cagst23824';
CREATE USER 'pcmadmin'@'%' IDENTIFIED BY 'cagst23824';
CREATE USER 'pcmuser'@'localhost' IDENTIFIED BY 'cagst23824';
CREATE USER 'pcmuser'@'%' IDENTIFIED BY 'cagst23824';

CREATE SCHEMA pcmdb DEFAULT CHARACTER SET utf8;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, TRIGGER ON pcmdb.* TO 'pcmadmin'@'localhost' IDENTIFIED BY 'cagst23824';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, TRIGGER ON pcmdb.* TO 'pcmadmin'@'%' IDENTIFIED BY 'cagst23824';
GRANT SELECT, INSERT, UPDATE, DELETE ON pcmdb.* TO 'pcmuser'@'localhost' IDENTIFIED BY 'cagst23824';
GRANT SELECT, INSERT, UPDATE, DELETE ON pcmdb.* TO 'pcmuser'@'%' IDENTIFIED BY 'cagst23824';
