CREATE USER 'sfmadmin'@'localhost' IDENTIFIED BY 'cagst23824';
CREATE USER 'sfmadmin'@'%' IDENTIFIED BY 'cagst23824';
CREATE USER 'sfmuser'@'localhost' IDENTIFIED BY 'cagst23824';
CREATE USER 'sfmuser'@'%' IDENTIFIED BY 'cagst23824';

CREATE SCHEMA sfmdb DEFAULT CHARACTER SET utf8;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, TRIGGER ON sfmdb.* TO 'sfmadmin'@'localhost' IDENTIFIED BY 'cagst23824';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, TRIGGER ON sfmdb.* TO 'sfmadmin'@'%' IDENTIFIED BY 'cagst23824';
GRANT SELECT, INSERT, UPDATE, DELETE ON sfmdb.* TO 'sfmuser'@'localhost' IDENTIFIED BY 'cagst23824';
GRANT SELECT, INSERT, UPDATE, DELETE ON sfmdb.* TO 'sfmuser'@'%' IDENTIFIED BY 'cagst23824';
